import { Resource } from './resource';

export const RESOURCES: Resource[] = 

[
  {
      id: 1,
      type: 'game',
      title: 'Concussion Game',
      location: 'https://www.superbetter.com/',
      platform: 'iOS, Android',
      subjects: '',
      summary: '',
      recommendedAges: 'All ages',
      description: 'SuperBetter increases resilience - the ability to stay strong, motivated and optimistic even in the face of difficult obstacles. Playing SuperBetter makes you more capable of getting through any tough situation—and more likely to achieve the goals that matter most to you. Proven results in just 10 minutes a day.',
      imageLink: ''
  }, /*,
  {
      id: 2,
      type: 'videos',
      title: 'The Great Courses',
      location: 'http://www.thegreatcourses.com/',
      platform: 'website videos - paid',
      summary: '',
  },
  {
      id: 3,
      type: 'game',
      title: 'Gambit Labs',
      location: 'http://gambit.mit.edu/index.php',
      platform: '',
      summary: 'There are tons here, need to be broken out individually',
      description: '',
      imageLink: ''
  },*/
  {
      id: 4,
      type: 'game',
      title: 'Minecraft',
      location: 'http://education.minecraft.net/',
      platform: 'PC',
      summary: '',
      subjects: '',
      description: 'Minecraft encourages millions of players to create, explore, and discover. We want to bring that passion into the classroom. Join us as we create a Minecraft built for learning',
      recommendedAges: '',
      imageLink: 'http://cdni.wired.co.uk/620x413/k_n/minecraft_5%20(1).jpg'
  },
  {
      id: 5,
      type: 'game',
      title: 'ScribbleNauts',
      location: '',
      platform: '3DS, Wii U, PC',
      summary: '',
      description: '5th Cell takes a step forward towards creating a balance between education and gameplay with Scribblenauts. The puzzle game makes an attempt to expand your vocabulary by encouraging you to use different words to solve things, but it also has a cutesy, gamer-y element of using those words in a video game manner. We haven’t seen something like that since the typing games of old like Mavis Beacon, who blend game activities with letter-typing reflex.',
      subjects: 'English, Art',
      recommendedAges: '',
      imageLink: 'http://wiiudaily.com/wp-content/uploads/2012/07/scribblenauts-unlimited-wii-u-screenshot-2.jpg?835c8a'
  },
  {
      id: 6,
      type: 'game',
      title: 'Oregon Trail',
      platform: 'PC',
      location: '',
      recommendedAges: 'Elementary, grades 3 - 6',
      summary: 'A PC game where students travel and experience the difficulties of travelling the Oregon Trail',
      description: 'The Oregon Trail is a computer game originally developed by Don Rawitsch, Bill Heinemann, and Paul Dillenberger in 1971 and produced by the Minnesota Educational Computing Consortium (MECC) in 1974. The original game was designed to teach school children about the realities of 19th century pioneer life on the Oregon Trail. The player assumes the role of a wagon leader guiding his or her party of settlers from Independence, Missouri, to Oregons Willamette Valley on the Oregon Trail via a covered wagon in 1848. The game is the first entry in the Oregon Trail series of games, and has since been released in many editions by various developers and publishers who have acquired rights to it, as well as inspiring a number of spinoffs (such as The Yukon Trail and The Amazon Trail) and the parody The Organ Trail.',
      subjects: 'History, Geography',
      imageLink: 'http://www.cafe.com/wp-content/uploads/2015/11/4_RefugeeTrail_Cholera.jpg'
  },
  {
      id: 7,
      type: 'game',
      title: 'Zoo Tycoon',
      platform: 'PC, XBox360, XBox One',
      location: '',
      recommendedAges: 'Everyone',
      summary: 'A series of games where you manage a zoo',
      description: 'Zoo Tycoon is a series of business simulation video games. The games focus around building and running successful zoo scenarios. The series was initially developed by Blue Fang Games and published by Microsoft Studios who later in 2001-2008 went on to create two stand-alone video games and seven expansion packs for PC and Macintosh platforms. With their contract with Microsoft ending in 2009, Blue Fang announced their official forums would close to incoming posts in June of 2008.[1] In 2013, Microsoft Studios released a new Zoo Tycoon game, developed by Frontier Developments exclusively for Xbox One and Xbox 360 in 2013. https://en.wikipedia.org/wiki/Zoo_Tycoon_(series)',
      subjects: 'Math, Economics',
      imageLink: 'http://screenshots.en.sftcdn.net/en/scrn/17000/17138/zoo-tycoon-5.jpg'
  },
 /* {
      id: 8,
      type: 'game',
      title: 'https://en.wikipedia.org/wiki/Professor_Layton'
  },*/
  {
      id: 9,
      type: 'game',
      title: 'Civilization Series',
      location: 'http://www.civilization.com/en/home/',
      platform: 'All',
      recommendedAges: 'Everyone',
      summary: 'A series of turn based strategy games.',
      description: 'Civilization is the game that lets you match wits with history’s greatest leaders. You start at the dawn of recorded history – 4,000 B.C., and the founding of the first cities – then nurture your society toward the Space Age. In the beginning, you’ll labor to simply survive while building your settlements, discovering new technologies and fending off barbarians. As your empire prospers, you’ll face competing civilizations guided by history’s most legendary figures: Alexander the Great, Napoleon, Genghis Khan, Julius Caesar and more. You’ll test your capacity for expansion and domination and your ability to outwit and outmaneuver those cunning and brilliant leaders.',
      subjects: 'Reading, Critical Thinking',
      imageLink: 'http://screenshots.en.sftcdn.net/en/scrn/3346000/3346642/civilization-v-gods-kings-04-700x430.jpg'
  },
  {
      id: 10,
      type: 'game',
      title: 'Braid',
      location: 'http://store.steampowered.com/app/26800/',
      platform: 'PC, XBox360',
      recommendedAges: 'Everyone',
      summary: 'A man named Tom must solve various puzzles involving time manipulation to save his princess.',
      description: 'Braid is a puzzle-platformer, drawn in a painterly style, where you can manipulate the flow of time in strange and unusual ways. From a house in the city, journey to a series of worlds and solve puzzles to rescue an abducted princess. http://store.steampowered.com/app/26800/',
      subjects: 'Critical Thinking',
      imageLink: 'http://learningworksforkids.com/wp-content/uploads/Braid-screen01.jpg'
  },
  {
      id: 11,
      type: 'game',
      title: 'The Witness',
      location: 'http://store.steampowered.com/app/210970/',
      platform: 'PC',
      recommendedAges: 'Everyone',
      summary: 'You wake up on an island with no idea who you are, how you got there, and a ton of puzzles to solve.',
      description: 'The Witness is a single-player game in an open world with dozens of locations to explore and over 500 puzzles. This game respects you as an intelligent player and it treats your time as precious. Theres no filler; each of those puzzles brings its own new idea into the mix. So, this is a game full of ideas. http://store.steampowered.com/app/210970/',
      subjects: 'Critical Thinking',
      imageLink: 'https://cdn3.vox-cdn.com/uploads/chorus_asset/file/5932597/shot_2015.10.27__time_12_29_n01.0.png'
  },
  {
      id: 12,
      type: 'game',
      title: 'Brain Age',
      location: '',
      platform: 'DS, 3DS',
      recommendedAges: 'Everyone',
      summary: 'A series of minigames to challenge your brain.',
      description: 'Activities include quickly solving simple math problems & counting people going in and out of a house simultaneously\nDraw pictures on the Touch Screen, or read classic literature out loud\nPlay Sudoku, the popular number puzzle game',
      subjects: 'Math, English, Brain Training',
      imageLink: 'http://www.cheatcc.com/imagesds/brainrev1.JPG'
  },
  {
      id: 13,
      type: 'game',
      title: 'Garage Band',
      location: 'http://www.apple.com/mac/garageband/',
      platform: 'OS X',
      recommendedAges: 'Everyone',
      summary: 'A tool for creating and editing music. It includes music lessons.',
      description: 'GarageBand is a whole music creation studio right inside your Mac — with a complete sound library that includes software instruments, presets for guitar and voice, and virtual session drummers. An intuitive interface makes it easy to learn, play, record, create, and share your hits worldwide. It’s never been easier to make music like a pro.',
      subjects: 'Music',
      imageLink: 'http://a4.mzstatic.com/us/r30/Purple7/v4/3f/2f/70/3f2f70e4-d265-b5b8-4170-84cd10341342/screen800x500.jpeg'
  },
  {
      id: 14,
      type: 'game',
      title: 'Rocksmith',
      location: 'http://rocksmith.ubi.com/rocksmith/en-us/home/',
      platform: 'PC, Xbox 360, PS3',
      recommendedAges: 'Teen',
      summary: 'A game that teaches you how to play guitar.',
      description: 'Plug any electric guitar or bass into your PC, Mac, Xbox One, Xbox 360, PlayStation® 4 system or PlayStation® 3 system, and join over 3 million people who have learned to play guitar with award-winning Rocksmith method. Learn to play guitar in 60 days. Get started, now!',
      subjects: 'Music',
      imageLink: 'http://cdn.gamer-network.net/2013/usgamer/Rocksmith-7.jpg'
  },
  {
      id: 15,
      type: 'game',
      title: 'Depression Quest',
      location: 'http://www.depressionquest.com/',
      platform: 'PC, OS X, Linux',
      recommendedAges: 'Teen',
      summary: 'A game that simulates living with Depression.',
      description: 'Depression Quest is an interactive fiction game where you play as someone living with depression. You are given a series of everyday life events and have to attempt to manage your illness, relationships, job, and possible treatment. This game aims to show other sufferers of depression that they are not alone in their feelings, and to illustrate to people who may not understand the illness the depths of what it can do to people. \n',
      subjects: 'Mental Health',
      imageLink: 'http://www.depressionquest.com/dq/ss1.jpg'
  },
  {
      id: 16,
      type: 'game',
      title: 'Typing of The Dead',
      location: '',
      platform: 'PC',
      recommendedAges: '*Elementary Grades 3+',
      summary: 'A series of games where you defeat zombies by typing words and sentences.',
      description: 'The Typing of the Dead is a modification of Segas 1998 light gun arcade game The House of the Dead 2 in which the gun is replaced by a computer keyboard. The player takes the role of a secret agent in a zombie-infested Venice and must quickly type letters, words and phrases in order to kill fast-advancing enemies.\nDespite falling under the criteria of \'edutainment\', the game was lauded by mainstream game critics for its humor, difficulty and originality. The PC version of The Typing of the Dead sold 120,000 units in 2003 https://en.wikipedia.org/wiki/The_Typing_of_the_Dead',
      subjects: 'English, Typing',
      imageLink: 'http://d2x7js8mtamps9.cloudfront.net/picture_1.jpg'
  },
  {
      id: 17,
      type: 'game',
      title: 'Reader Rabbit series',
      location: '',
      platform: 'PC, Wii',
      recommendedAges: '*Elementary 1-3',
      summary: 'A series of games that teaches math and reading skills through minigames',
      description: 'The first game in the series taught language arts, featuring a variety of simple games designed to teach schoolchildren basic reading and spelling skills. Originally, the title characters name was changed to reflect a change in subject, as with Math Rabbit, but it has apparently since been decided to retain the characters original name regardless of the subject area covered by a particular game.',
      subjects: 'Math, Reading',
      imageLink: 'http://cf.shacknews.com/images/20110513/vaqghu0srf3domvqbcuwwqvdedp66crh_18058.jpg'
  },
  {
      id: 18,
      type: 'game',
      title: 'Math Blaster series',
      location: '',
      platform: 'PC',
      recommendedAges: '*Elementary 1-6',
      summary: 'A series of games where you help an alien save the planet by solving math problems.',
      description: 'The Blaster Learning System is an educational video game series originally created by Davidson, but is now owned by Knowledge Adventure. Titles in the series have been produced for various computer systems, video game consoles, and as stand-alone handheld units. Originally, the series simply taught mathematics, but eventually expanded to other subjects, such as language arts (reading) and science. Due to the popularity of the original Math Blaster series, Davidson introduced Reading Blaster in 1994, which also went on to become successful. A Science Blaster was introduced 1996, but did not reach the same popularity as its predecessors. https://en.wikipedia.org/wiki/Blaster_Learning_System',
      subjects: 'Math',
      imageLink: 'http://gamefabrique.com/storage/screenshots/snes/math-blaster-episode1-04.png'
  },
  {
      id: 19,
      type: 'game',
      title: 'Operation Neptune',
      location: '',
      platform: 'PC',
      recommendedAges: '*Elementary Grades 4+',
      summary: 'A game where you explore the ocean and make progress by solving challenging math problems.',
      description: 'A team of astronauts and scientists have begun a secret research project on a distant planet. The research teams results were sent back to Earth on the \'Galaxy space capsule\', which malfunctioned, crashed into the ocean, and broke into many pieces. The capsule included several data canisters, each of which contains small snippets of the scientists story, which is revealed to the player as the game progresses and data canisters are found. The capsule also contained some toxic chemicals, which have begun to leak out and threaten the health of the worlds sea life. A recovery mission, codenamed Operation Neptune, is sent to recover the pieces of the capsule. https://en.wikipedia.org/wiki/Operation_Neptune_(video_game)',
      subjects: 'Math',
      imageLink: 'http://img.gamefaqs.net/screens/6/7/3/gfs_86150_2_8.jpg'
  },
  {
      id: 20,
      type: 'game',
      title: 'Marios Early Years',
      location: '',
      platform: 'PC, SNES',
      recommendedAges: '*Preschool-Grade 1',
      summary: 'Characters from the Super Mario series teach children basic math and reading.',
      description: '',
      subjects: 'Math, Reading',
      imageLink: 'https://i.ytimg.com/vi/K7wWXfGaThw/hqdefault.jpg'
  },
  {
      id: 21,
      type: 'game',
      title: 'Myst',
      location: '',
      platform: 'All',
      recommendedAges: 'Everyone',
      summary: 'A series of games where the story unfolds via solving puzzles',
      description: 'Myst is a graphic adventure puzzle video game designed and directed by the brothers Robyn and Rand Miller. It was developed by Cyan, Inc., published by Brøderbund, and initially released on the Macintosh platform on September 24, 1993. https://en.wikipedia.org/wiki/Myst',
      subjects: 'Critical Thinking',
      imageLink: 'http://www.mystjourney.com/img/screenshots/myst-34.jpg'
  },
  {
      id: 22,
      type: 'game',
      title: 'Carmen Sandiego',
      location: '',
      platform: 'PC',
      recommendedAges: '*Elementary Grades 3+',
      summary: 'A series of games where you solve extraordinary thefts using geography and history skills.',
      description: '',
      subjects: 'History, Geography',
      imageLink: 'https://i.ytimg.com/vi/sEsRNYdZIQw/hqdefault.jpg'
  },
  {
      id: 23,
      type: 'game',
      title: 'Clue Finders',
      location: '',
      platform: 'PC',
      recommendedAges: 'Elementary Grades 3-6',
      summary: 'A series of games where a group of kids solve various mysteries using problem solving skills.',
      description: 'The ClueFinders is a series of Edutainment Games from The Learning Company in which the eponymous Kid Heroes have Scooby-Doo type exploits.',
      subjects: 'Math, Reading, Critical Thinking',
      imageLink: 'http://a4.mzstatic.com/us/r30/Purple/v4/1f/bf/1b/1fbf1b02-fa9e-8499-3141-ee00234f1bb7/screen800x500.jpeg'
  },
  {
      id: 24,
      type: 'game',
      title: 'Sesame Street ABC/123',
      location: '',
      platform: 'PC, NES',
      recommendedAges: '*Preschool-Grade 1',
      summary: 'The characters from Sesame street teach young children basic reading, math, and problem solving through a series of minigames.',
      description: 'Sesame Street: ABC/123 is an Edutainment game, developed by Rare Ltd. and published by Hi-Tech, which was released in 1991. http://www.amazon.com/Sesame-Street-ABC-Nintendo-Entertainment-System/dp/B003ACHV70',
      subjects: 'Math, Reading, Critical Thinking',
      imageLink: 'http://nintendolegend.com/wp-content/uploads/2013/08/sesame_street_abc_nes_gameplay_screenshot_5.png'
  },
  {
      id: 25,
      type: 'game',
      title: 'Donalds Alphabet Chase',
      location: '',
      platform: 'PC',
      recommendedAges: '*Preschool-Grade 1',
      summary: 'A game where you help Donald Duck find the letters of the alphabet scattered throughout his home.',
      description: 'The letters of the alphabet got out of Donald Ducks toybox and are scattered throughout his home. You must use your reading and problem solving skills to get them back.',
      subjects: 'English',
      imageLink: 'http://img.squakenet.com/snapshot/7554/74770-DonaldsAlphabetChase.jpg'
  },
  {
      id: 26,
      type: 'game',
      title: '3D Dinosaur Adventure',
      location: '',
      platform: 'PC',
      recommendedAges: '*Elementary',
      summary: 'A series of minigames where you encounter and learn about dinosaurs',
      subjects: 'History, Science',
      description: '',
      imageLink: 'https://i.ytimg.com/vi/Np_dQHAM7po/hqdefault.jpg'
  },
  {
      id: 27,
      type: 'game',
      title: 'Plague Inc.',
      location: 'http://www.ndemiccreations.com/en/22-plague-inc',
      platform: 'PC, iOS, Android',
      recommendedAges: '*Grades 6+',
      summary: 'A Risk style strategy game where you attempt to wipe out humanity with a deadly disease.',
      description: 'Can you infect the world? Plague Inc. is a unique mix of high strategy and terrifyingly realistic simulation with over 700 million games played!\nYour pathogen has just infected Patient Zero. Now you must bring about the end of human history by evolving a deadly, global Plague whilst adapting against everything humanity can do to defend itself.\n\nBrilliantly executed with innovative gameplay and built from the ground up for the iPhone, iPad, Android & Windows Phone, Plague Inc. evolves the strategy genre and pushes mobile gaming (and you) to new levels. It’s You vs. the world - only the strongest can survive!',
      subjects: 'Critical Thinking, Science, Geography',
      imageLink: 'http://icdn.computec.de/videos/img/medium/2014/2/56452.jpg'
  },
  {
      id: 28,
      type: 'game',
      title: 'Mixed-Up Mother Goose',
      location: '',
      platform: 'PC',
      recommendedAges: '*Preschool-Grades 1-3',
      summary: 'A game where you go around as a small child fixing nursery rhymes.',
      description: 'The storyline of the game is very simple, as is common in games for children. One night, while preparing for bed, a child (which is the players avatar) is sent into the dreamlike world of Mother Goose, who desperately needs his or her help. All the nursery rhymes in the land have gotten mixed up, with none of the inhabitants possessing the items necessary for their rhyme to exist. And so, the child will find themselves helping Humpty Dumpty find a ladder to scramble onto a wall, bringing the little lamb back to Mary and seeking out a pail for Jack and Jill, among others. https://en.wikipedia.org/wiki/Mixed-Up_Mother_Goose',
      subjects: 'English',
      imageLink: 'http://s.uvlist.net/l/y2005/10/3957.jpg'
  },
  {
      id: 29,
      type: 'game',
      title: 'Sim City',
      location: 'http://www.ea.com/sim-city',
      platform: 'PC',
      recommendedAges: '*Grades 4+',
      summary: 'A series of simulation games where you build and manage a city.',
      description: 'In SimCity, the player is given the task of founding and developing a city, while maintaining the happiness of the citizens and keeping a stable budget. https://en.wikipedia.org/wiki/SimCity',
      subjects: 'Economics, Politics',
      imageLink: 'http://web-vassets.ea.com/Assets/Resources/Others/SimCity2000_screen2WebEmbed.jpg'
  },
  {
      id: 30,
      type: 'game',
      title: 'Super Seekers Series',
      location: '',
      platform: 'PC',
      recommendedAges: '*Elementary',
      summary: 'A series of puzzle adventure games that challenge your reading and math skills.',
      description: 'A series of side scrolling, adventure puzzle games by the Learning Company. The Master of Mischief makes, well, mischief in each game and the Super Seeker must foil his scheme via solving math and reading puzzles.',
      subjects: 'Math, English',
      imageLink: 'https://upload.wikimedia.org/wikipedia/en/2/27/Treasure_Mountain_Learning_Company.png'
  },
  {
      id: 31,
      type: 'game',
      title: 'Word Rescue',
      location: 'http://store.steampowered.com/app/358340/',
      platform: 'PC',
      recommendedAges: '*Elementary Grades 1-3',
      summary: 'A game where you find letters to spell out words with the help of a book worm.',
      description: 'This is an engrossing educational game with vivid EGA/VGA graphics and support for Adlib and Sound Blaster. Using the Duke Nukem graphical system, Word Rescue has state-of-the-art dual-screen scrolling graphics similar to whats seen on the Super Nintendo and Sega Genesis home gaming systems. Even \'grown-ups\' will like Word Rescue! \n\nPlay as either a girl or a boy. Visit amazing locations on your word-finding adventure, as you hunt for missing words. Dark caves, rocky cliffs, deserts, happy towns, haunted houses, funny factories and creepy dungeons are just some of the places youll explore.',
      subjects: 'English',
      imageLink: 'http://image.dosgamesarchive.com/screenshots/wordrescue6.gif'
  },
  {
      id: 32,
      type: 'game',
      title: 'Dungeon Keeper',
      location: 'https://www.gog.com/game/dungeon_keeper',
      platform: 'PC',
      recommendedAges: '*Grades 6+',
      summary: 'A series of games where you build dungeons to corrupt cities',
      description: 'Dungeon Keeper is a strategy video game developed by Bullfrog Productions and released by Electronic Arts in July 1997 for DOS. In Dungeon Keeper, the player builds and manage a dungeon while protecting it from invading hero characters intent on stealing the players accumulated treasures and killing various monsters. https://en.wikipedia.org/wiki/Dungeon_Keeper',
      subjects: 'Critical Thinking',
      imageLink: 'http://dungeonkeeperdownload.weebly.com/uploads/2/3/4/4/23445916/6522947_orig.jpg'
  }
];